
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import KinkySwapEscrowContractArtifactJson from '../../target/kinky_swap_escrow-KinkySwapEscrow.json' with { type: 'json' };
export const KinkySwapEscrowContractArtifact = loadContractArtifact(KinkySwapEscrowContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract KinkySwapEscrow;
 */
export class KinkySwapEscrowContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, KinkySwapEscrowContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, KinkySwapEscrowContract.artifact, wallet) as Promise<KinkySwapEscrowContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<KinkySwapEscrowContract>(PublicKeys.default(), wallet, KinkySwapEscrowContractArtifact, KinkySwapEscrowContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<KinkySwapEscrowContract>(publicKeys, wallet, KinkySwapEscrowContractArtifact, KinkySwapEscrowContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof KinkySwapEscrowContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<KinkySwapEscrowContract['methods'][M]>
  ) {
    return new DeployMethod<KinkySwapEscrowContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      KinkySwapEscrowContractArtifact,
      KinkySwapEscrowContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return KinkySwapEscrowContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(KinkySwapEscrowContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'escrow_ids'> {
      return {
        escrow_ids: {
      slot: new Fr(1n),
    }
      } as ContractStorageLayout<'escrow_ids'>;
    }
    

  public static get notes(): ContractNotes<'UintNote' | 'ValueNote'> {
    return {
      UintNote: {
          id: new NoteSelector(1),
        },
ValueNote: {
          id: new NoteSelector(0),
        }
    } as ContractNotes<'UintNote' | 'ValueNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** escrow(hashlock: field, token_address: struct, amount: integer, nonce: field, withdraw_block: integer, taker: struct) */
    escrow: ((hashlock: FieldLike, token_address: AztecAddressLike, amount: (bigint | number), nonce: FieldLike, withdraw_block: (bigint | number), taker: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw(secret: field, recipient: struct) */
    withdraw: ((secret: FieldLike, recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
