[package]
name = "kinky_swap_escrow"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.9", directory="noir-projects/aztec-nr/aztec" }
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.9", directory="noir-projects/aztec-nr/value-note"}
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.9", directory="noir-projects/noir-contracts/contracts/app/token_contract"}
easy_private_state = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.9", directory="noir-projects/aztec-nr/easy-private-state"}